{{- if .Values.ingress }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.ingress.tls.cert }}
  namespace: istio-system
spec:
  secretName: {{ .Values.ingress.tls.certName }}
  commonName: {{ .Values.ingress.dns.name }}
  dnsNames:
    - {{ .Values.ingress.dns.name }}
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  duration: 2160h
  renewBefore: 360h
{{- end }}